[tool.poetry]
name = "webservice"
version = "0.1.0"
description = ""
authors = ["majed_wp12 <majedwp12@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.2"
uvicorn = "^0.31.1"
pandas = "2.2.3"
requests = "2.32.3"
characters = "^0.1.0"
jdatetime = "5.0.0"
bs4 = "0.0.2"
aiohttp = "3.10.10"
unsync = "1.4.0"
persiantools = "4.2.0"
ipython = "8.28.0"
lxml = "^5.3.0"
gunicorn = "^23.0.0"
aiohappyeyeballs = "2.4.3"
aiosignal = "1.3.1"
asttokens = "2.4.1"
async-timeout = "4.0.3"
attrs = "24.2.0"
beautifulsoup4 = "4.12.3"
certifi = "2024.8.30"
charset-normalizer = "3.4.0"
decorator = "5.1.1"
exceptiongroup = "1.2.2"
executing = "2.1.0"
frozenlist = "1.4.1"
idna = "3.10"
jalali-core = "1.0.0"
jedi = "0.19.1"
matplotlib-inline = "0.1.7"
multidict = "6.1.0"
numpy = "2.1.2"
parso = "0.8.4"
pexpect = "4.9.0"
prompt-toolkit = "3.0.48"
propcache = "0.2.0"
ptyprocess = "0.7.0"
pure-eval = "0.2.3"
pygments = "2.18.0"
python-dateutil = "2.9.0.post0"
pytz = "2024.2"
six = "1.16.0"
soupsieve = "2.6"
stack-data = "0.6.3"
traitlets = "5.14.3"
typing-extensions = "4.12.2"
tzdata = "2024.2"
urllib3 = "2.2.3"
wcwidth = "0.2.13"
yarl = "1.15.5"
python-nginx = "^1.5.7"
prometheus-client = "^0.21.0"
prometheus-fastapi-instrumentator = "^7.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
